### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by davisshannon** [r00tten/VTI-Cosplay#1]
Getting these errors trying when passing in a yara file.

Traceback (most recent call last):
  File "vti-cosplay.py", line 174, in <module>
    main()
  File "vti-cosplay.py", line 114, in main
    pDic = yara.parse()
  File "/home/ubuntu/VTI-Cosplay/utils/yaraParser.py", line 506, in parse
    conditionParsed = self.conditionParser()
  File "/home/ubuntu/VTI-Cosplay/utils/yaraParser.py", line 434, in conditionParser
    conArr = self.conditionNormalizer(conStr)
  File "/home/ubuntu/VTI-Cosplay/utils/yaraParser.py", line 150, in conditionNormalizer
    stack.pop()
IndexError: pop from empty list

Here are the rules in my yar file:

/*
   YARA Rule Set
   Author: yarGen Rule Generator
   Date: 2022-01-08
   Identifier: pysa-new
   Reference: https://github.com/Neo23x0/yarGen
*/

/* Rule Set ----------------------------------------------------------------- */

/* Super Rules ------------------------------------------------------------- */

rule _pysa_0_pysa_1_pysa_3_pysa_2_pysa_4_0 {
   meta:
      description = "pysa-new - from files pysa-0.exe, pysa-1.exe, pysa-3.exe, pysa-2.exe, pysa-4.exe"
      author = "yarGen Rule Generator"
      reference = "https://github.com/Neo23x0/yarGen"
      date = "2022-01-08"
      hash1 = "0433efd9ba06378eb6eae864c85aafc8b6de79ef6512345294e9e379cc054c3d"
      hash2 = "164cb8e82d7e07cca0409925cadd8be5e3e8e07db88526ff7fe87596c6a6bd07"
      hash3 = "7c774062bc55e2d0e869d5d69820aa6e3b759454dbc926475b4db6f7f2b6cb14"
      hash4 = "44f1def68aef34687bfacf3668e56873f9d603fc6741d5da1209cc55bdc6f1f9"
      hash5 = "f602319a51dfad374687a6d18f87c9f8e7b9cab956a4993c2ed83e7adad6e2db"
   strings:
      $s1 = ".?AV?$TF_CryptoSystemBase@VPK_Encryptor@CryptoPP@@V?$TF_Base@VRandomizedTrapdoorFunction@CryptoPP@@VPK_EncryptionMessageEncoding" ascii
      $s2 = "update.bat" fullword ascii
      $s3 = ".?AV?$AlgorithmImpl@VCBC_Encryption@CryptoPP@@V?$CipherModeFinalTemplate_CipherHolder@V?$BlockCipherFinal@$0A@VEnc@Rijndael@Cryp" ascii
      $s4 = ".?AV?$CipherModeFinalTemplate_CipherHolder@V?$BlockCipherFinal@$0A@VEnc@Rijndael@CryptoPP@@@CryptoPP@@VCBC_Encryption@2@@CryptoP" ascii
      $s5 = "        <requestedExecutionLevel level='asInvoker' uiAccess='false' />" fullword ascii
      $s6 = " operation failed with error " fullword ascii
      $s7 = ".?AV?$TF_ObjectImpl@VTF_EncryptorBase@CryptoPP@@U?$TF_CryptoSchemeOptions@V?$TF_ES@URSA@CryptoPP@@V?$OAEP@VSHA1@CryptoPP@@VP1363" ascii
      $s8 = ".?AV?$TF_ObjectImplBase@VTF_EncryptorBase@CryptoPP@@U?$TF_CryptoSchemeOptions@V?$TF_ES@URSA@CryptoPP@@V?$OAEP@VSHA1@CryptoPP@@VP" ascii
      $s9 = ".?AV?$TF_EncryptorImpl@U?$TF_CryptoSchemeOptions@V?$TF_ES@URSA@CryptoPP@@V?$OAEP@VSHA1@CryptoPP@@VP1363_MGF1@2@@2@H@CryptoPP@@UR" ascii
      $s10 = ".?AV?$TF_ObjectImpl@VTF_EncryptorBase@CryptoPP@@U?$TF_CryptoSchemeOptions@V?$TF_ES@URSA@CryptoPP@@V?$OAEP@VSHA1@CryptoPP@@VP1363" ascii
      $s11 = ".?AV?$TF_ObjectImplBase@VTF_EncryptorBase@CryptoPP@@U?$TF_CryptoSchemeOptions@V?$TF_ES@URSA@CryptoPP@@V?$OAEP@VSHA1@CryptoPP@@VP" ascii
      $s12 = ".?AV?$AlgorithmImpl@VTF_EncryptorBase@CryptoPP@@V?$TF_ES@URSA@CryptoPP@@V?$OAEP@VSHA1@CryptoPP@@VP1363_MGF1@2@@2@H@2@@CryptoPP@@" ascii
      $s13 = ".?AV?$TF_EncryptorImpl@U?$TF_CryptoSchemeOptions@V?$TF_ES@URSA@CryptoPP@@V?$OAEP@VSHA1@CryptoPP@@VP1363_MGF1@2@@2@H@CryptoPP@@UR" ascii
      $s14 = "Check out our website, we just posted there new updates for our partners: http://pysa2bitc5ldeyfak4seeruqymqs4sj5wt5qkcq7aoyg4h2" ascii
      $s15 = " for this public key" fullword ascii
      $s16 = "Check out our website, we just posted there new updates for our partners: http://pysa2bitc5ldeyfak4seeruqymqs4sj5wt5qkcq7aoyg4h2" ascii
      $s17 = "Also, be aware that we downloaded files from your servers and in case of non-payment we will be forced to upload them on our web" ascii
      $s18 = " Type Descriptor'" fullword ascii
      $s19 = " is not a valid key length" fullword ascii
      $s20 = "toPP@@@CryptoPP@@VCBC_Encryption@2@@2@@CryptoPP@@" fullword ascii
   condition:
      ( uint16(0) == 0x5a4d and filesize < 2000KB and ( 8 of them )
      ) or ( all of them )
}

rule _pysa_0_pysa_3_pysa_2_pysa_4_1 {
   meta:
      description = "pysa-new - from files pysa-0.exe, pysa-3.exe, pysa-2.exe, pysa-4.exe"
      author = "yarGen Rule Generator"
      reference = "https://github.com/Neo23x0/yarGen"
      date = "2022-01-08"
      hash1 = "0433efd9ba06378eb6eae864c85aafc8b6de79ef6512345294e9e379cc054c3d"
      hash2 = "7c774062bc55e2d0e869d5d69820aa6e3b759454dbc926475b4db6f7f2b6cb14"
      hash3 = "44f1def68aef34687bfacf3668e56873f9d603fc6741d5da1209cc55bdc6f1f9"
      hash4 = "f602319a51dfad374687a6d18f87c9f8e7b9cab956a4993c2ed83e7adad6e2db"
   strings:
      $s1 = ":6<F<6=F=" fullword ascii /* hex encoded string 'oo' */
      $s2 = "7!878c8" fullword ascii /* Goodware String - occured 1 times */
      $s3 = "6C7V7e7" fullword ascii /* Goodware String - occured 1 times */
      $s4 = ";;;L;{;" fullword ascii /* Goodware String - occured 1 times */
      $s5 = "<)<8<t<" fullword ascii /* Goodware String - occured 1 times */
      $s6 = "q2w2{2" fullword ascii /* Goodware String - occured 1 times */
      $s7 = "=+>N>]>" fullword ascii /* Goodware String - occured 1 times */
      $s8 = "<B<`<w<" fullword ascii /* Goodware String - occured 2 times */
      $s9 = "1\"1:1B1q1" fullword ascii /* Goodware String - occured 2 times */
      $s10 = "6#7?7F7" fullword ascii /* Goodware String - occured 2 times */
      $s11 = ">8?N?d?m?x?" fullword ascii /* Goodware String - occured 2 times */
      $s12 = ":%:,:3:" fullword ascii /* Goodware String - occured 2 times */
      $s13 = "4%494L4" fullword ascii /* Goodware String - occured 2 times */
      $s14 = "4C4K4|4" fullword ascii /* Goodware String - occured 2 times */
      $s15 = ":,;1;D;" fullword ascii /* Goodware String - occured 2 times */
      $s16 = "4%4*4>4" fullword ascii /* Goodware String - occured 2 times */
      $s17 = "f8j8n8r8v8z8~8" fullword ascii /* Goodware String - occured 2 times */
      $s18 = "2A3I3o3" fullword ascii /* Goodware String - occured 2 times */
      $s19 = ";0;[;~;" fullword ascii /* Goodware String - occured 2 times */
      $s20 = "989A9L9" fullword ascii /* Goodware String - occured 3 times */
   condition:
      ( uint16(0) == 0x5a4d and filesize < 2000KB and ( 8 of them )
      ) or ( all of them )
}

rule _pysa_1_pysa_3_2 {
   meta:
      description = "pysa-new - from files pysa-1.exe, pysa-3.exe"
      author = "yarGen Rule Generator"
      reference = "https://github.com/Neo23x0/yarGen"
      date = "2022-01-08"
      hash1 = "164cb8e82d7e07cca0409925cadd8be5e3e8e07db88526ff7fe87596c6a6bd07"
      hash2 = "7c774062bc55e2d0e869d5d69820aa6e3b759454dbc926475b4db6f7f2b6cb14"
   strings:
      $s1 = ":4:<:D:L:T:\\:d:l:p:t:x:" fullword ascii
      $s2 = "9 989H9L9\\9`9d9h9l9p9t9x9|9" fullword ascii /* Goodware String - occured 1 times */
      $s3 = "Mwnh0#F" fullword ascii
      $s4 = ":,:0:8:@:H:L:T:h:" fullword ascii /* Goodware String - occured 1 times */
      $s5 = ">$><>L>P>`>d>t>x>" fullword ascii /* Goodware String - occured 1 times */
      $s6 = "<$<,<@<H<P<X<\\<`<d<l<" fullword ascii /* Goodware String - occured 1 times */
      $s7 = "4$4@4`4l4" fullword ascii /* Goodware String - occured 1 times */
      $s8 = "3 3@3T3d3x3" fullword ascii /* Goodware String - occured 1 times */
      $s9 = "74787P7`7d7l7" fullword ascii /* Goodware String - occured 1 times */
      $s10 = "<(<,<0<4<8<<<@<D<X<\\<l<p<t<x<|<" fullword ascii /* Goodware String - occured 1 times */
      $s11 = "J;N;R;V;" fullword ascii /* Goodware String - occured 1 times */
      $s12 = "6l6p6t6" fullword ascii /* Goodware String - occured 1 times */
      $s13 = "303@3D3L3d3t3x3|3" fullword ascii /* Goodware String - occured 1 times */
      $s14 = ">8>X>`>h>t>" fullword ascii /* Goodware String - occured 1 times */
      $s15 = "444D4H4X4\\4l4p4t4|4" fullword ascii /* Goodware String - occured 1 times */
      $s16 = "5$5,545<5D5L5T5\\5d5|5" fullword ascii /* Goodware String - occured 1 times */
      $s17 = ": :4:8:H:L:\\:`:p:t:x:|:" fullword ascii /* Goodware String - occured 1 times */
      $s18 = "64686P6`6d6h6l6p6t6x6|6" fullword ascii /* Goodware String - occured 1 times */
      $s19 = "4 4(4@4" fullword ascii /* Goodware String - occured 1 times */
      $s20 = "=$=(=8=<=@=D=H=L=P=T=X=`=x=" fullword ascii /* Goodware String - occured 2 times */
   condition:
      ( uint16(0) == 0x5a4d and filesize < 2000KB and ( 8 of them )
      ) or ( all of them )
}

**Comment by r00tten** [comment]
Hello @davisshannon,

Currently the VTI-Cosplay supports single rule per file. Hence, during the parsing routine it gets exception.
